/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Prestake } from "./Prestake";
export * as factories from "./factories";
export { Prestake__factory } from "./factories/Prestake__factory";
